"""add reviews table

Revision ID: 72aaa14602a5
Revises: f92c1989960f
Create Date: 2025-04-17 02:15:49.548779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72aaa14602a5'
down_revision: Union[str, None] = 'f92c1989960f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('reviews', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.add_column('reviews', sa.Column('book_uid', sa.Uuid(), nullable=True))
    op.add_column('reviews', sa.Column('create_date', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('reviews', sa.Column('update_date', postgresql.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'users', ['user_uid'], ['uid'])
    op.create_foreign_key(None, 'reviews', 'books', ['book_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'update_date')
    op.drop_column('reviews', 'create_date')
    op.drop_column('reviews', 'book_uid')
    op.drop_column('reviews', 'user_uid')
    op.drop_column('reviews', 'review_text')
    # ### end Alembic commands ###
